# Generated by Django 4.2.4 on 2023-08-25 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0015_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='completed',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='session_id',
        ),
    ]
