# Generated by Django 4.2.4 on 2023-08-25 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storeapp', '0017_cart_completed_cart_owner_cart_session_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='cart_id',
            new_name='id',
        ),
    ]
